spring:
  batch:
    job:
      enabled: false
    initialize-schema: always
  quartz:
    jdbc:
      initialize-schema: always
    job-store-type: jdbc
    scheduler-name: study-Quartz
    properties:
      org.quartz.threadPool.threadCount: 5
  datasource:
    url: jdbc:mysql://localhost/batch?serverTimezone=UTC
    username: user
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    org:
      quartz: trace
    study: trace
